### ISSUE TITLE
Uploading files in avi format results in broken videos

### ISSUE THREAD

**Issue by MirceaKitsune** [dtube/ipfs-uploader#10]
Upon uploading a few old videos which were recorded in the avi format, I noticed some issues with how DTube handles the video. The ones I can name off the top of my head include:

- The uploader informed me that the format cannot be previewed while I was uploaded. I was additionally unable to generate a snap (thumbnail) after the upload process.
- Once the video does upload, you're only able to play the 480p version. Attempting to play the Source results in an error saying "source missing or unsupported format".
- When the video appears on a channel or in a search, the bottom-right tag showing you how long the video is doesn't appear over the thumbnail.
- When positioning the cursor on the play bar, you don't see a thumbnail preview of the video, but instead a black box saying "PREVIEW NOT AVAILABLE", even if a sprite image exists.

I'm proposing one of three things: Either allow the DTube player to support less common formats (avi, mpg, mkv), convert the source as well and treat it that as the original file, or tell the user to use a supported format (mp4, ogv) and don't allow them to upload in other formats. The current functionality results in partly broken videos which don't have all features available.

**Comment by superkoala38** [comment]
It's all Dtube issues, not uploader issues because your 480p version works, please use our discord for support
