### ISSUE TITLE
A proposal Logo for DTube

### ISSUE THREAD

**Issue by gitgamer** [dtube/ipfs-uploader#3]
Hi !!! Thanks for your project ...

I maked a proposal for new logo ..

If you want , you can visit here...

https://steemit.com/utopian-io/@orelmely/working-with-dtube-proposal-logo-and-animation-contribution-fully-editable-vector-format

**Comment by skzap** [comment]
We actually updated our logo today, feel free to check it out:

https://busy.org/dtube/@heimindanger/d-tube-0-6-pushing-it-to-the-limit
