### ISSUE TITLE
Upload erroron d.tube

### ISSUE THREAD

**Issue by daslicht** [dtube/ipfs-uploader#9]
Hi,
I am not sure where to post errors for dtube, so I start here.

When I upload a vide and try to save it on d.tube I get : 
```
×
Error
permlink.size() > STEEM_MIN_PERMLINK_LENGTH && permlink.size() < STEEM_MAX_PERMLINK_LENGTH: Permlink is not a valid size.
```
![](https://i.imgur.com/ZoclKVr.png)
Whats wrong ?

**Comment by daslicht** [comment]
where is teh correct to post such kind of issues please?

**Comment by superkoala38** [comment]
It's not uploader issue but dtube issue. Please use our discord for support
